"""Shared reference data — regulation-agnostic country-to-region mapping."""

# Complete country→region mapping (239 countries)
_COUNTRY_TO_REGION = {
    # EEA (33 entries incl. ECB/ESM/EU institutions)
    "BE": "EEA", "LU": "EEA", "DE": "EEA", "EE": "EEA", "GR": "EEA",
    "ES": "EEA", "FR": "EEA", "IE": "EEA", "IT": "EEA", "CY": "EEA",
    "MT": "EEA", "NL": "EEA", "AT": "EEA", "PT": "EEA", "SI": "EEA",
    "SK": "EEA", "FI": "EEA", "4F": "EEA", "4S": "EEA", "DK": "EEA",
    "SE": "EEA", "BG": "EEA", "CZ": "EEA", "HR": "EEA", "HU": "EEA",
    "LT": "EEA", "LV": "EEA", "PL": "EEA", "RO": "EEA", "4A": "EEA",
    "IS": "EEA", "LI": "EEA", "NO": "EEA",
    # Europe non-EEA (20)
    "AD": "Europe", "AL": "Europe", "BA": "Europe", "BY": "Europe",
    "FO": "Europe", "GG": "Europe", "GI": "Europe", "IM": "Europe",
    "JE": "Europe", "MD": "Europe", "ME": "Europe", "MK": "Europe",
    "RS": "Europe", "RU": "Europe", "SM": "Europe", "TR": "Europe",
    "UA": "Europe", "GB": "Europe", "VA": "Europe", "CH": "Europe",
    # Africa (56)
    "DZ": "Africa", "EG": "Africa", "LY": "Africa", "MA": "Africa",
    "TN": "Africa", "AO": "Africa", "BF": "Africa", "BI": "Africa",
    "BJ": "Africa", "BW": "Africa", "CD": "Africa", "CF": "Africa",
    "CG": "Africa", "CI": "Africa", "CM": "Africa", "CV": "Africa",
    "DJ": "Africa", "ER": "Africa", "ET": "Africa", "GA": "Africa",
    "GH": "Africa", "GM": "Africa", "GN": "Africa", "GQ": "Africa",
    "GW": "Africa", "IO": "Africa", "KE": "Africa", "KM": "Africa",
    "LR": "Africa", "LS": "Africa", "MG": "Africa", "ML": "Africa",
    "MR": "Africa", "MU": "Africa", "MW": "Africa", "MZ": "Africa",
    "NA": "Africa", "NE": "Africa", "NG": "Africa", "RW": "Africa",
    "SC": "Africa", "SD": "Africa", "SH": "Africa", "SL": "Africa",
    "SN": "Africa", "SO": "Africa", "ST": "Africa", "SS": "Africa",
    "SZ": "Africa", "TD": "Africa", "TG": "Africa", "TZ": "Africa",
    "UG": "Africa", "ZA": "Africa", "ZM": "Africa", "ZW": "Africa",
    # North America (3)
    "CA": "NorthAmerica", "GL": "NorthAmerica", "US": "NorthAmerica",
    # South America (45 — includes Central America, Caribbean, Mexico per ESMA)
    "AG": "SouthAmerica", "AI": "SouthAmerica", "AW": "SouthAmerica",
    "BB": "SouthAmerica", "BM": "SouthAmerica", "BQ": "SouthAmerica",
    "BS": "SouthAmerica", "BZ": "SouthAmerica", "CR": "SouthAmerica",
    "CU": "SouthAmerica", "CW": "SouthAmerica", "DM": "SouthAmerica",
    "DO": "SouthAmerica", "GD": "SouthAmerica", "GT": "SouthAmerica",
    "HN": "SouthAmerica", "HT": "SouthAmerica", "JM": "SouthAmerica",
    "KN": "SouthAmerica", "KY": "SouthAmerica", "LC": "SouthAmerica",
    "MS": "SouthAmerica", "MX": "SouthAmerica", "NI": "SouthAmerica",
    "PA": "SouthAmerica", "SV": "SouthAmerica", "SX": "SouthAmerica",
    "TC": "SouthAmerica", "TT": "SouthAmerica", "VC": "SouthAmerica",
    "VG": "SouthAmerica", "VI": "SouthAmerica", "AR": "SouthAmerica",
    "BO": "SouthAmerica", "BR": "SouthAmerica", "CL": "SouthAmerica",
    "CO": "SouthAmerica", "EC": "SouthAmerica", "FK": "SouthAmerica",
    "GY": "SouthAmerica", "PE": "SouthAmerica", "PY": "SouthAmerica",
    "SR": "SouthAmerica", "UY": "SouthAmerica", "VE": "SouthAmerica",
    # Middle East (17)
    "IL": "MiddleEast", "IR": "MiddleEast", "AE": "MiddleEast",
    "BH": "MiddleEast", "IQ": "MiddleEast", "KW": "MiddleEast",
    "OM": "MiddleEast", "QA": "MiddleEast", "SA": "MiddleEast",
    "YE": "MiddleEast", "AM": "MiddleEast", "AZ": "MiddleEast",
    "GE": "MiddleEast", "JO": "MiddleEast", "LB": "MiddleEast",
    "PS": "MiddleEast", "SY": "MiddleEast",
    # Asia Pacific (65)
    "AF": "AsiaPacific", "BD": "AsiaPacific", "BN": "AsiaPacific",
    "BT": "AsiaPacific", "CN": "AsiaPacific", "HK": "AsiaPacific",
    "ID": "AsiaPacific", "IN": "AsiaPacific", "JP": "AsiaPacific",
    "KG": "AsiaPacific", "KH": "AsiaPacific", "KP": "AsiaPacific",
    "KR": "AsiaPacific", "KZ": "AsiaPacific", "LA": "AsiaPacific",
    "LK": "AsiaPacific", "MM": "AsiaPacific", "MN": "AsiaPacific",
    "MO": "AsiaPacific", "MV": "AsiaPacific", "MY": "AsiaPacific",
    "NP": "AsiaPacific", "PH": "AsiaPacific", "PK": "AsiaPacific",
    "SG": "AsiaPacific", "TH": "AsiaPacific", "TJ": "AsiaPacific",
    "TL": "AsiaPacific", "TM": "AsiaPacific", "TW": "AsiaPacific",
    "UZ": "AsiaPacific", "VN": "AsiaPacific", "AU": "AsiaPacific",
    "FJ": "AsiaPacific", "FM": "AsiaPacific", "KI": "AsiaPacific",
    "MH": "AsiaPacific", "MP": "AsiaPacific", "NC": "AsiaPacific",
    "NR": "AsiaPacific", "NZ": "AsiaPacific", "PF": "AsiaPacific",
    "PG": "AsiaPacific", "PN": "AsiaPacific", "PW": "AsiaPacific",
    "SB": "AsiaPacific", "TO": "AsiaPacific", "TV": "AsiaPacific",
    "VU": "AsiaPacific", "WF": "AsiaPacific", "WS": "AsiaPacific",
    "CC": "AsiaPacific", "CX": "AsiaPacific", "HM": "AsiaPacific",
    "NF": "AsiaPacific", "AS": "AsiaPacific", "GU": "AsiaPacific",
    "UM": "AsiaPacific", "CK": "AsiaPacific", "NU": "AsiaPacific",
    "TK": "AsiaPacific", "AQ": "AsiaPacific", "BV": "AsiaPacific",
    "GS": "AsiaPacific", "TF": "AsiaPacific",
}
